/**
 * Référentiel unique des libellés d’audit (journal + filtres) pour éviter les « Action non référencée ».
 *
 * Toute nouvelle action backend métier doit être ajoutée ici avant merge.
 */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  AUTH_LOGIN: "Connexion utilisateur",
  AUTH_ACCOUNT_LOCKED: "[Utilisateurs] Compte verrouillé après échecs de connexion",
  AUTH_SET_PASSWORD: "Changement de mot de passe",
  AUTH_FIRST_LOGIN_COMPLETED: "Première connexion finalisée",
  USER_UNLOCK: "[Utilisateurs] Déverrouillage de compte",
  USER_PREFERENCES_THEME_UPDATE: "[Utilisateurs] Changement de thème (clair / sombre)",
  USERS_LIST: "Consultation de la liste utilisateurs",
  USER_CREATE: "Création d'utilisateur",
  USER_RESET_PASSWORD: "Réinitialisation du mot de passe",
  USER_UPDATE_ROLE: "Modification du rôle utilisateur",
  USER_UPDATE_PROFILE: "Modification du profil utilisateur",
  USER_UPDATE_ACCESS: "Modification des accès utilisateur",
  USER_DEACTIVATE: "Désactivation d'utilisateur",
  DATA_SITE_CREATE: "Création de site",
  DATA_SITE_UPDATE: "Modification de site",
  DATA_SITE_DELETE: "Suppression de site",
  DATA_INTERVENANT_CREATE: "Création d'intervenant",
  DATA_INTERVENANT_UPDATE: "Modification d'intervenant",
  DATA_INTERVENANT_DELETE: "Suppression d'intervenant",
  DATA_TYPE_CREATE: "Création de type d'anomalie",
  DATA_TYPE_UPDATE: "Modification de type d'anomalie",
  DATA_TYPE_DELETE: "Suppression de type d'anomalie",
  DATA_HOLIDAY_CREATE: "[Rondes] Ajout d'un jour férié",
  DATA_HOLIDAY_UPDATE: "[Rondes] Modification d'un jour férié",
  DATA_HOLIDAY_DELETE: "[Rondes] Suppression d'un jour férié",
  DATA_RONDE_MOTIF_CREATE: "[Référentiels] Création d'un motif de ronde",
  DATA_RONDE_MOTIF_UPDATE: "[Référentiels] Modification d'un motif de ronde",
  DATA_RONDE_MOTIF_DELETE: "[Référentiels] Suppression d'un motif de ronde",
  DATA_RONDE_PLANNED_PROFILE_CREATE: "[Référentiels] Création d'un profil de planification des rondes",
  DATA_RONDE_PLANNED_PROFILE_UPDATE: "[Référentiels] Modification d'un profil de planification des rondes",
  DATA_RONDE_PLANNED_PROFILE_DELETE: "[Référentiels] Suppression d'un profil de planification des rondes",
  DATA_RONDE_PLANNED_PROFILE_DEACTIVATE: "[Rondes] Désactivation d'un profil de planification (rondes clôturées liées)",
  DATA_RONDE_PLANNED_PROFILE_WORD_TEMPLATE_INSTALL:
    "[Référentiels] Installation du modèle Word d'un profil de planification des rondes",
  DATA_RONDE_PLANNED_PROFILE_PLANNING_END: "[Rondes] Fin de planification d'un profil (date de fin)",
  DATA_RONDE_PLANNED_PROFILE_VALIDATION: "[Rondes] Validation d'un profil de planification par un responsable",
  DATA_RONDE_PLANNED_PROFILE_CLOSURE_UPDATE: "[Rondes] Modification des champs Word et clôture d'un profil de planification",
  DATA_FORM_VARIABLES_SAVE: "[Paramètres] Enregistrement des variables de formulaires et attributions",
  DATA_DOCUMENT_TEMPLATE_INSTALL: "[Référentiels] Copie d'un modèle Word dans data/templates",
  DATA_TEMPLATE_ASSIGNMENT_CREATE: "[Paramètres] Attribution d'un modèle personnalisé",
  DATA_TEMPLATE_ASSIGNMENT_UPDATE: "[Paramètres] Modification d'une attribution de modèle personnalisé",
  DATA_TEMPLATE_ASSIGNMENT_DELETE: "[Paramètres] Suppression d'une attribution de modèle personnalisé",
  DATA_INTERVENTION_WORD_EXTRA_FIELDS_SAVE:
    "[Référentiels] Enregistrement des champs complémentaires export Word (interventions)",
  DATA_RONDE_PLANNED_INTERVENANT_REQUIRED: "[Référentiels] Prestataire obligatoire pour un profil de planification des rondes",
  DATA_RONDE_PLANNED_INTERVENANT_NOT_FOUND: "[Référentiels] Prestataire invalide (profil planification rondes)",
  DATA_RONDE_PLANNED_RANDOM_PERIOD: "[Référentiels] Période jour/nuit obligatoire (ronde aléatoire)",
  DATA_RONDE_PLANNED_RANGE_DATES: "[Référentiels] Dates de plage de planification incomplètes",
  DATA_RONDE_PLANNED_RANGE_ORDER: "[Référentiels] Ordre des dates de plage de planification invalide",
  DATA_RONDE_PLANNED_PLANNING_FROM_REQUIRED: "[Référentiels] Date de début de validité du profil de ronde obligatoire",
  DATA_RONDE_PLANNED_PLANNING_ORDER: "[Référentiels] Ordre des dates de validité du profil de ronde invalide",
  DATA_RONDE_PLANNED_RANDOM_WINDOW: "[Référentiels] Fenêtre horaire aléatoire invalide ou incomplète",
  DATA_RONDE_PLANNED_RANDOM_ROUNDS: "[Référentiels] Nombre de rondes aléatoires invalide",
  DATA_IMPORT_BATCH_RESULT: "Résultat d'import en masse",
  DATA_IMPORT_BATCH_ROW_ERROR: "Erreur ligne import en masse",
  DATA_WRITER_CONFIG_GENERATED: "[Paramètres] Génération du fichier gts_writer-config.json",
  FRANSOR_RESPONSABLE_CREATE: "[Fransor] Ajout d'un responsable",
  FRANSOR_RESPONSABLE_UPDATE: "[Fransor] Modification d'un responsable",
  FRANSOR_RESPONSABLE_DELETE: "[Fransor] Suppression d'un responsable",
  FRANSOR_CLOSURE_CREATE: "[Fransor] Ajout d'une exception",
  FRANSOR_CLOSURE_UPDATE: "[Fransor] Modification d'une exception",
  FRANSOR_CLOSURE_DELETE: "[Fransor] Suppression d'une exception",
  FRANSOR_ENTRY_CREATE: "[Fransor] Ajout d'une saisie ouverture/fermeture",
  FRANSOR_ENTRY_UPDATE: "[Fransor] Modification d'une saisie ouverture/fermeture",
  MAIN_COURANTE_CREATE: "[Main courante] Création d'une information",
  MAIN_COURANTE_CREATE_IDEMPOTENT: "[Main courante] Création d'une information (idempotente)",
  MAIN_COURANTE_UPDATE_OPERATOR: "[Main courante] Modification d'une information (opérateur)",
  MAIN_COURANTE_MANAGER_ACTION: "[Main courante] Action manager (historique)",
  MAIN_COURANTE_MANAGER_SUIVRE: "[Main courante] Information marquée comme \"À suivre\"",
  MAIN_COURANTE_MANAGER_CLOTURE: "[Main courante] Information marquée comme \"Clôturée\"",
  MAIN_COURANTE_MANAGER_REOPEN: "[Main courante] Information rouverte",
  INTERVENTION_CREATE: "[Intervention] Création d'une intervention",
  INTERVENTION_UPDATE: "[Intervention] Modification d'une intervention",
  INTERVENTION_CLOSE: "[Intervention] Intervention clôturée",
  INTERVENTION_REOPEN: "[Intervention] Intervention rouverte",
  INTERVENTION_CANCEL: "[Intervention] Intervention annulée",
  INTERVENTION_BILLING_UPDATE: "[Intervention] Mise à jour facturation",
  INTERVENTION_SITE_PENDING_CREATE: "[Intervention] Ajout d'un site en attente de validation",
  INTERVENTION_INTERVENANT_PENDING_CREATE: "[Intervention] Ajout d'un intervenant en attente de validation",
  INTERVENTION_SITE_PENDING_RESOLVE: "[Intervention] Validation d'un site en attente",
  INTERVENTION_INTERVENANT_PENDING_RESOLVE: "[Intervention] Validation d'un intervenant en attente",
  INTERVENTION_SITE_PENDING_DELETE: "[Intervention] Suppression d'un site en attente",
  INTERVENTION_INTERVENANT_PENDING_DELETE: "[Intervention] Suppression d'un intervenant en attente",
  RONDE_CREATE: "[Rondes] Création d'une ronde",
  RONDE_UPDATE: "[Rondes] Modification d'une ronde",
  RONDE_CLOSE: "[Rondes] Ronde clôturée",
  RONDE_CANCEL: "[Rondes] Ronde annulée",
  RONDE_REOPEN: "[Rondes] Ronde rouverte",
  RONDE_BATCH_CREATE: "[Rondes] Création en lot de demandes exceptionnelles",
  RONDE_BATCH_UPDATE: "[Rondes] Modification commune d’un lot de demandes exceptionnelles",
  RONDE_BATCH_CANCEL: "[Rondes] Annulation en lot d’un lot de demandes exceptionnelles",
  RONDE_BATCH_DELETE: "[Rondes] Suppression en lot d’un lot de demandes exceptionnelles",
  RONDE_EXCEPTIONAL_AUTO_CLOSE_BATCH: "[Rondes] Clôture automatique des rondes exceptionnelles échues",
  MAIN_COURANTE_ARCHIVE_BATCH: "[Main courante] Archivage automatique des entrées clôturées",
  MAIN_COURANTE_ARCHIVE_SKIP_WRITER_UNAVAILABLE: "[Main courante] Archivage reporté (writer indisponible)",
  DB_QUARTER_ROTATION: "[Système] Rotation trimestrielle de la base active",
  DB_ACTIVE_SWITCH: "[Système] Changement manuel de base active",
  DB_ARCHIVE_SESSION_ENTER: "[Système] Ouverture d'une archive en mode édition",
  DB_ARCHIVE_SESSION_EXIT: "[Système] Retour à la base active locale",
  GARDIENNAGE_CREATE: "[Gardiennage] Création d'un gardiennage",
  GARDIENNAGE_BATCH_CREATE: "[Gardiennage] Création en lot d'un gardiennage planifié",
  GARDIENNAGE_BATCH_CANCEL: "[Gardiennage] Annulation en lot d'un gardiennage",
  GARDIENNAGE_UPDATE: "[Gardiennage] Modification d'un gardiennage",
  GARDIENNAGE_DELETE: "[Gardiennage] Suppression d'un gardiennage",
  GARDIENNAGE_BATCH_DELETE: "[Gardiennage] Suppression en lot d'un gardiennage",
  GARDIENNAGE_STATUS_PLANIFIE: "[Gardiennage] Gardiennage remis en planifié",
  GARDIENNAGE_STATUS_ACTIF: "[Gardiennage] Gardiennage activé",
  GARDIENNAGE_STATUS_CLOTURE: "[Gardiennage] Gardiennage clôturé",
  GARDIENNAGE_STATUS_ANNULE: "[Gardiennage] Gardiennage annulé",
  GARDIENNAGE_STATUS_CHANGE: "[Gardiennage] Changement de statut",
  GARDIENNAGE_REOPEN: "[Gardiennage] Gardiennage rouvert",
  GARDIENNAGE_AUTO_CLOSE_BATCH: "[Gardiennage] Clôture automatique des prestations échues"
};

export function formatAuditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] || action;
}

export function formatAuditActionLabelOrUnknown(action: string): string {
  return AUDIT_ACTION_LABELS[action] || `Action non référencée (${action})`;
}
